//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmerchant
    {
        public int Merchantid { get; set; }
        public Nullable<int> Categoryid { get; set; }
        public string Merchantname { get; set; }
        public string Photo { get; set; }
    
        public virtual tblCategory1 tblCategory1 { get; set; }
    }
}
